#!/bin/bash
case $1 in
  -c | check )
    python ai_blue/pm/check.py
    ;;
  -U | upgrade )
    python ai_blue/pm/upgrade.py
    ;;
  -l | local )
    ai_blue/pm/local.sh $2
    ;;
#  -i | install )
#    ai_blue/pm/install.sh
#    echo "install.sh"
#    ;;
#  -u | update )
#    ai_blue/pm/update.sh
#    echo "update.sh"
#    ;;
#  -r | remove )
#    ai_blue/pm/remove.sh
#    echo "remove.sh"
#    ;;
  * )
    echo -e "\e[31mInvalid option or initilized \`blue help\`!"
    echo
    echo -e "\e[34mCommands:\e[32m"
    echo "  check   | -c    -->   Check if there is a new update."
    echo "                        And will let you download the update if there is one."
    echo "  upgrade | -U    -->   Update the system, if there is an update."
    echo "  local   | -l    -->   Update the system using a local file."
#    echo "  [! COMING SOON !] install  --> Install a package from the BlueOS repository."
#    echo "  [! COMING SOON !] update   --> Update a package from the BlueOS repository.
#               (If no package is specified, all will be updated.)"
#    echo "  [! COMING SOON !] remove   --> Remove a package that comes from the BlueOS repository."
#    echo
#    echo -e "\e[32mUsage: blue [COMMAND] [OPTIONS]"
    ;;
esac; shift;
